# ansible-playbook lab04.yml
---
- hosts: all
  remote_user: cisco
  gather_facts: false
  vars_files:
    - ./group_vars/all.yml

  tasks:
    - name: Ospf configuration
      cisco.ios.ios_config:
        src: "./templates/ospf.j2"

    - name: Loopbacks configuration
      cisco.ios.ios_config:
        src: "./templates/loopback.j2"

    - name: Ospf auth configuration
      cisco.ios.ios_config:
        src: "./templates/ospf_auth.j2"

    # print osfp info
    - name: ospf neighbor
      ios_command:
        commands:
          - show ip ospf neighbor
      register: ospf_neighbor

    - name: ospf routes
      ios_command:
        commands:
          - show ip route ospf
      register: ospf_route

    
    - name: "vars"
      set_fact:
        osp_neighbor_parsed: "{{ospf_neighbor.stdout[0] | regex_findall('[\\n]{1}(?:[0-9]{1,3}\\.){3}[0-9]{1,3}')}}"
    
    - debug:
        msg: "Neighbour IDs: {{ item.replace('\\n', '').replace('\n', '') }}"
      loop: "{{ osp_neighbor_parsed }}"

    - debug:
        msg: "Number of learned routes: {{ospf_route.stdout[0] | regex_findall('(?:[0-9]{1,3}\\.){3}[0-9]{1,3}[,]') | count}}"

# print config 
#
#    - name: config
#      ios_command:
#       commands:
#          - show run | exclude !
#      register: result_config
#
#    - name: Print config
#      debug:
#        var: result_config
