# ansible-playbook lab04.yml
---
- hosts: all
  remote_user: cisco
  gather_facts: false
  vars_files:
    - ./group_vars/all.yml

  tasks:
    - name: Ospf configuration
      cisco.ios.ios_config:
        src: "./templates/ospf.j2"

    - name: Loopbacks configuration
      cisco.ios.ios_config:
        src: "./templates/loopback.j2"

    - name: Ospf auth configuration
      cisco.ios.ios_config:
        src: "./templates/ospf_auth.j2"

    # print config (for personal use and debugging)
    - name: config
      ios_command:
        commands:
          - show run | exclude !
      register: result_config

    - name: Print config
      debug:
        var: result_config

    # print osfp info
    - name: config
      ios_command:
        commands:
          - show ip ospf neighbor
          - show ip route ospf
      register: ospf_config

    - name: Print ospf config
      debug:
        var: ospf_config.stdout_lines
